services:
  card-web:
    build:
      context: .
      args:
        UID: ${DOCKER_USER_UID}
        GID: ${DOCKER_USER_GID}
        PROJECT: ${DOCKER_PROJECT_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    user: ${DOCKER_USER_UID}:${DOCKER_USER_GID}
    env_file:
      - .env
    ports:
      - ${DOCKER_PORT}:3000
    volumes:
      - ${DOCKER_SSH}:/home/node/.ssh
      - ${DOCKER_PROJECT}:/home/node/${DOCKER_PROJECT_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 114.114.114.114
      - 1.1.1.1
    command:
      - sh
      - -c
      - |
          yarn install
          yarn build
          yarn start
